//===========================================================================//
//
// Purpose: An offline Steam client for platforms without Steam.
//
// CS:GO's engine and client quit at startup unless a Steam client hands out
// its interfaces (CSteamAPIContext::Init) and reports a logged-in individual
// user. This provides every interface CS:GO asks for: all methods default to
// empty/false results (generated by scripts/gen_offline_steam.py), and the
// overrides below describe a single offline user who owns CS:GO, with no
// friends, lobbies, cloud storage or Steam networking.
//
//===========================================================================//

#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "steam/steam_api.h"
#include "steam/isteamgameserver.h"
#include "steam/isteamgameserverstats.h"

#include "steam_offline.h"

namespace
{

const uint32 k_unOfflineAppID = 730;

// a stable local identity; account ID 1 is never a real CS:GO player
CSteamID OfflineSteamID()
{
	return CSteamID( 1, k_EUniversePublic, k_EAccountTypeIndividual );
}

const char *OfflinePersonaName()
{
	const char *pszName = getenv( "STEAM_PERSONA_NAME" );
	return ( pszName && *pszName ) ? pszName : "Player";
}

time_t g_tStart = time( NULL );

//-----------------------------------------------------------------------------
// Null interfaces: every method returns an empty result
//-----------------------------------------------------------------------------
#define NULL_INTERFACE( iface ) \
	class CNull##iface : public iface \
	{ \
	public:

NULL_INTERFACE( ISteamClient )
#include "generated/ISteamClient.inl"
};
NULL_INTERFACE( ISteamUser )
#include "generated/ISteamUser.inl"
};
NULL_INTERFACE( ISteamFriends )
#include "generated/ISteamFriends.inl"
};
NULL_INTERFACE( ISteamUtils )
#include "generated/ISteamUtils.inl"
};
NULL_INTERFACE( ISteamMatchmaking )
#include "generated/ISteamMatchmaking.inl"
};
NULL_INTERFACE( ISteamMatchmakingServers )
#include "generated/ISteamMatchmakingServers.inl"
};
NULL_INTERFACE( ISteamUserStats )
#include "generated/ISteamUserStats.inl"
};
NULL_INTERFACE( ISteamApps )
#include "generated/ISteamApps.inl"
};
NULL_INTERFACE( ISteamNetworking )
#include "generated/ISteamNetworking.inl"
};
NULL_INTERFACE( ISteamRemoteStorage )
#include "generated/ISteamRemoteStorage.inl"
};
NULL_INTERFACE( ISteamScreenshots )
#include "generated/ISteamScreenshots.inl"
};
NULL_INTERFACE( ISteamHTTP )
#include "generated/ISteamHTTP.inl"
};
NULL_INTERFACE( ISteamUnifiedMessages )
#include "generated/ISteamUnifiedMessages.inl"
};
NULL_INTERFACE( ISteamController )
#include "generated/ISteamController.inl"
};
NULL_INTERFACE( ISteamUGC )
#include "generated/ISteamUGC.inl"
};
NULL_INTERFACE( ISteamAppList )
#include "generated/ISteamAppList.inl"
};
NULL_INTERFACE( ISteamMusic )
#include "generated/ISteamMusic.inl"
};
NULL_INTERFACE( ISteamMusicRemote )
#include "generated/ISteamMusicRemote.inl"
};
NULL_INTERFACE( ISteamHTMLSurface )
#include "generated/ISteamHTMLSurface.inl"
};
NULL_INTERFACE( ISteamInventory )
#include "generated/ISteamInventory.inl"
};
NULL_INTERFACE( ISteamVideo )
#include "generated/ISteamVideo.inl"
};

//-----------------------------------------------------------------------------
// The offline user
//-----------------------------------------------------------------------------
class COfflineSteamUser : public CNullISteamUser
{
public:
	virtual HSteamUser GetHSteamUser() { return k_hOfflineSteamUser; }
	virtual bool BLoggedOn() { return true; }
	virtual CSteamID GetSteamID() { return OfflineSteamID(); }
	virtual int GetPlayerSteamLevel() { return 1; }
	virtual HAuthTicket GetAuthSessionTicket( void *pTicket, int cbMaxTicket, uint32 *pcbTicket )
	{
		if ( pcbTicket )
			*pcbTicket = 0;
		return k_HAuthTicketInvalid;
	}
};

class COfflineSteamFriends : public CNullISteamFriends
{
public:
	virtual const char *GetPersonaName() { return OfflinePersonaName(); }
	virtual EPersonaState GetPersonaState() { return k_EPersonaStateOnline; }
	virtual EPersonaState GetFriendPersonaState( CSteamID steamIDFriend )
	{
		return steamIDFriend == OfflineSteamID() ? k_EPersonaStateOnline : k_EPersonaStateOffline;
	}
	virtual const char *GetFriendPersonaName( CSteamID steamIDFriend )
	{
		return steamIDFriend == OfflineSteamID() ? OfflinePersonaName() : "";
	}
	virtual const char *GetPlayerNickname( CSteamID steamIDPlayer ) { return NULL; }
	virtual EFriendRelationship GetFriendRelationship( CSteamID steamIDFriend ) { return k_EFriendRelationshipNone; }
};

class COfflineSteamUtils : public CNullISteamUtils
{
public:
	virtual uint32 GetSecondsSinceAppActive() { return (uint32)( time( NULL ) - g_tStart ); }
	virtual uint32 GetSecondsSinceComputerActive() { return GetSecondsSinceAppActive(); }
	virtual EUniverse GetConnectedUniverse() { return k_EUniversePublic; }
	virtual uint32 GetServerRealTime() { return (uint32)time( NULL ); }
	virtual const char *GetIPCountry() { return "US"; }
	virtual uint8 GetCurrentBatteryPower() { return 255; } // "on AC power"
	virtual uint32 GetAppID() { return k_unOfflineAppID; }
	virtual bool IsOverlayEnabled() { return false; }
	virtual const char *GetSteamUILanguage() { return "english"; }
};

class COfflineSteamApps : public CNullISteamApps
{
public:
	virtual bool BIsSubscribed() { return true; }
	virtual bool BIsSubscribedApp( AppId_t appID ) { return appID == k_unOfflineAppID; }
	virtual const char *GetCurrentGameLanguage() { return "english"; }
	virtual const char *GetAvailableGameLanguages() { return "english"; }
};

//-----------------------------------------------------------------------------
// The client: hands out one instance of each interface
//-----------------------------------------------------------------------------
class COfflineSteamClient : public CNullISteamClient
{
public:
	virtual HSteamPipe CreateSteamPipe() { return k_hOfflineSteamPipe; }
	virtual bool BReleaseSteamPipe( HSteamPipe hSteamPipe ) { return true; }
	virtual HSteamUser ConnectToGlobalUser( HSteamPipe hSteamPipe ) { return k_hOfflineSteamUser; }

	virtual ISteamUser *GetISteamUser( HSteamUser, HSteamPipe, const char * ) { return &m_User; }
	virtual ISteamFriends *GetISteamFriends( HSteamUser, HSteamPipe, const char * ) { return &m_Friends; }
	virtual ISteamUtils *GetISteamUtils( HSteamPipe, const char * ) { return &m_Utils; }
	virtual ISteamMatchmaking *GetISteamMatchmaking( HSteamUser, HSteamPipe, const char * ) { return &m_Matchmaking; }
	virtual ISteamMatchmakingServers *GetISteamMatchmakingServers( HSteamUser, HSteamPipe, const char * ) { return &m_MatchmakingServers; }
	virtual ISteamUserStats *GetISteamUserStats( HSteamUser, HSteamPipe, const char * ) { return &m_UserStats; }
	virtual ISteamApps *GetISteamApps( HSteamUser, HSteamPipe, const char * ) { return &m_Apps; }
	virtual ISteamNetworking *GetISteamNetworking( HSteamUser, HSteamPipe, const char * ) { return &m_Networking; }
	virtual ISteamRemoteStorage *GetISteamRemoteStorage( HSteamUser, HSteamPipe, const char * ) { return &m_RemoteStorage; }
	virtual ISteamScreenshots *GetISteamScreenshots( HSteamUser, HSteamPipe, const char * ) { return &m_Screenshots; }
	virtual ISteamHTTP *GetISteamHTTP( HSteamUser, HSteamPipe, const char * ) { return &m_HTTP; }
	virtual ISteamUnifiedMessages *GetISteamUnifiedMessages( HSteamUser, HSteamPipe, const char * ) { return &m_UnifiedMessages; }
	virtual ISteamController *GetISteamController( HSteamUser, HSteamPipe, const char * ) { return &m_Controller; }
	virtual ISteamUGC *GetISteamUGC( HSteamUser, HSteamPipe, const char * ) { return &m_UGC; }
	virtual ISteamAppList *GetISteamAppList( HSteamUser, HSteamPipe, const char * ) { return &m_AppList; }
	virtual ISteamMusic *GetISteamMusic( HSteamUser, HSteamPipe, const char * ) { return &m_Music; }
	virtual ISteamMusicRemote *GetISteamMusicRemote( HSteamUser, HSteamPipe, const char * ) { return &m_MusicRemote; }
	virtual ISteamHTMLSurface *GetISteamHTMLSurface( HSteamUser, HSteamPipe, const char * ) { return &m_HTMLSurface; }
	virtual ISteamInventory *GetISteamInventory( HSteamUser, HSteamPipe, const char * ) { return &m_Inventory; }
	virtual ISteamVideo *GetISteamVideo( HSteamUser, HSteamPipe, const char * ) { return &m_Video; }

private:
	COfflineSteamUser m_User;
	COfflineSteamFriends m_Friends;
	COfflineSteamUtils m_Utils;
	CNullISteamMatchmaking m_Matchmaking;
	CNullISteamMatchmakingServers m_MatchmakingServers;
	CNullISteamUserStats m_UserStats;
	COfflineSteamApps m_Apps;
	CNullISteamNetworking m_Networking;
	CNullISteamRemoteStorage m_RemoteStorage;
	CNullISteamScreenshots m_Screenshots;
	CNullISteamHTTP m_HTTP;
	CNullISteamUnifiedMessages m_UnifiedMessages;
	CNullISteamController m_Controller;
	CNullISteamUGC m_UGC;
	CNullISteamAppList m_AppList;
	CNullISteamMusic m_Music;
	CNullISteamMusicRemote m_MusicRemote;
	CNullISteamHTMLSurface m_HTMLSurface;
	CNullISteamInventory m_Inventory;
	CNullISteamVideo m_Video;
};

} // namespace

ISteamClient *OfflineSteamClient()
{
	static COfflineSteamClient s_Client;
	return &s_Client;
}
