#! /usr/bin/env python
# encoding: utf-8

top = '.'
PROJECT_NAME = 'gcsdk'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'gcclient.cpp',
		'gcconstants.cpp',
		'gclogger.cpp',
		'gcmsg.cpp',
		'job.cpp',
		'jobmgr.cpp',
		'jobtime.cpp',
		'messagelist.cpp',
		'msgprotobuf.cpp',
		'netpacket.cpp',
		'netpacketpool.cpp',
		'protobufsharedobject.cpp',
		'sharedobject.cpp',
		'sharedobjectcache.cpp',
		'gcclient_sharedobjectcache.cpp',
		'steamextra/misc.cpp',
		'steamextra/rtime.cpp',
		'steamextra/steamid.cpp',
		'steamextra/tier1/hashglobals.cpp',
		'steamextra/tier1/tsmempool.cpp',
		'steamextra/tier1/tsmultimempool.cpp',
		'steamextra/tier1/murmurhash3.cpp',
		'workthreadpool.cpp',
		'webapi_response.cpp',
		'JSON_parser/JSON_parser.c',
		'../game/shared/generated_proto/steammessages.pb.cc',
		'../game/shared/generated_proto/gcsystemmsgs.pb.cc',
		'../game/shared/generated_proto/gcsdk_gcmessages.pb.cc',
		'../game/shared/generated_proto/base_gcmessages.pb.cc',
		'../game/shared/generated_proto/econ_gcmessages.pb.cc',
		'../game/shared/generated_proto/tf_gcmessages.pb.cc',
	]

	includes = [
		'../protobuf',
		'../thirdparty/protobuf-2.6.1/src',
		'../game/shared/generated_proto',
		'.',
		'JSON_parser',
		'steamextra',
		'../',
		'../public',
		'../public/gcsdk',
		'../public/tier0',
		'../public/tier1',
		'../common',
	]

	defines = ['TF']

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		export_includes = [
			'.',
			'steamextra',
			'../public',
			'../public/gcsdk',
			'../game/shared/generated_proto',
		],
		defines  = defines,
		use      = ['protobuf', 'tier0', 'tier1', 'vstdlib'],
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
