#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'client'

def options(opt):
	return

games = {
	'hl2': ['client_base.vpc', 'client_hl2.vpc'],
	'hl2mp': ['client_base.vpc', 'client_hl2mp.vpc'],
	'hl1': ['client_base.vpc', 'client_hl1.vpc'],
	'episodic': ['client_base.vpc', 'client_episodic.vpc'],
	'portal': ['client_base.vpc', 'client_portal.vpc'],
	'hl1mp': ['client_base.vpc', 'client_hl1mp.vpc'],
	'cstrike': ['client_base.vpc', 'client_cstrike.vpc'],
	'dod': ['client_base.vpc', 'client_dod.vpc'],
	'tf': ['client_base.vpc', 'client_econ_base.vpc', 'client_tf.vpc'],
	'csgo': ['client_base.vpc', 'client_econ_base.vpc', 'client_cstrike15.vpc'],
}

_CODE_EXTS = ('.c', '.cc', '.cpp', '.cxx')

_TF_SKIP_STEAM = (
	'/workshop/',
	'steampublishedfiles/',
	'sixense/',
	'ugc_utils',
	'publish_file_dialog',
	'published_files.cpp',
	'client_community_market',
	'tf_steamstats',
	'tf_gameserver_management',
	'maps_workshop',
	'abuse_report',
)

_CSGO_SKIP = (
	'/scaleform/',
	'steamoverlay',
	'steamworks_gamestats',
	'ugc_workshop',
	'workshop_manager',
	'dedicated_server_ugc',
	'filesystem_init.cpp',
	'linux_support.cpp',
	'/utils/common/',
	'sixense/',
	'zip_utils.cpp',
	'lumpfiles.cpp',
	'/public/xzip.cpp',
	'/public/xunzip.cpp',
)

def _code_sources(files, skip=()):
	out = []
	for s in files:
		low = s.replace('\\', '/').lower()
		if not low.endswith(_CODE_EXTS):
			continue
		if any(tok in low for tok in skip):
			continue
		out.append(s)
	return out

def _tf_sources():
	return [
		'../shared/tf/tf_gcmessages.cpp',
	]

def _tf_includes():
	return [
		'../../protobuf',
		'../../thirdparty/protobuf-2.6.1/src',
		'../shared/generated_proto',
		'../../public/gcsdk',
		'../../gcsdk',
		'../../gcsdk/steamextra',
	]

def _csgo_proto_sources():
	return [
		'generated_proto/cstrike15_usermessages.pb.cc',
		'generated_proto/cstrike15_gcmessages.pb.cc',
		'generated_proto/base_gcmessages.pb.cc',
		'generated_proto/steammessages.pb.cc',
		'generated_proto/netmessages.pb.cc',
		'generated_proto/network_connection.pb.cc',
	]

def _csgo_includes():
	return [
		'../../protobuf',
		'../../thirdparty/protobuf-2.6.1/src',
		'./generated_proto',
		'../shared/generated_proto',
		'../../public/gcsdk',
		'../../gcsdk',
		'../../gcsdk/steamextra',
		'./cstrike15',
		'./cstrike15/gameui',
		'./cstrike15/VGUI',
		'../shared/cstrike15',
		'../shared/econ',
		'./econ',
	]

def _strip_defines(defines, drop):
	out = []
	for d in defines:
		key = d.split('=')[0]
		if key in drop:
			continue
		out.append(d)
	return out

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'game_controls',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../vgui2/include',
		'../../vgui2/controls',
		'../shared'
	]

	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'RT',
		'ZLIB'
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android' and not bld.env.IOS:
		install_path += '/'+bld.env.GAMES+'/bin'

	source = [ 'in_touch.cpp' ]
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	skip = ()
	if bld.env.GAMES == 'tf':
		skip = _TF_SKIP_STEAM
	elif bld.env.GAMES == 'csgo':
		skip = _CSGO_SKIP
	source += _code_sources(game["sources"], skip) + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	defines = game["defines"]

	if bld.env.GAMES == 'tf':
		source += _tf_sources()
		includes = _tf_includes() + includes
		libs += ['gcsdk', 'protobuf', 'JPEG']
		defines.append('NO_STEAM=1')
	elif bld.env.GAMES == 'csgo':
		source += _csgo_proto_sources()
		includes = _csgo_includes() + includes
		libs += ['gcsdk', 'protobuf', 'JPEG']
		defines.append('NO_STEAM=1')
		defines = _strip_defines(defines, ('INCLUDE_SCALEFORM',))

	if 'PROTECTED_THINGS_ENABLE' in defines:
		defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
