// Generated by scripts/gen_null_scaleform.py from public/scaleformui/scaleformui.h -- do not edit.

// IUIMarshalHelper
virtual SFVALUEARRAY Params_GetArgs( SFPARAMS params ) { return SFVALUEARRAY( 0, NULL ); }
virtual unsigned int Params_GetNumArgs( SFPARAMS params ) { return 0; }
virtual bool Params_ArgIs( SFPARAMS params, unsigned int index, _ValueType v ) { return false; }
virtual SFVALUE Params_GetArg( SFPARAMS params, int index = 0 ) { return NULL; }
virtual _ValueType Params_GetArgType( SFPARAMS params, int index = 0 ) { return static_cast< _ValueType >( 0 ); }
virtual double Params_GetArgAsNumber( SFPARAMS params, int index = 0 ) { return 0; }
virtual bool Params_GetArgAsBool( SFPARAMS params, int index = 0 ) { return false; }
virtual const char* Params_GetArgAsString( SFPARAMS params, int index = 0 ) { return ""; }
virtual const wchar_t* Params_GetArgAsStringW( SFPARAMS params, int index = 0 ) { return L""; }
virtual void Params_DebugSpew( SFPARAMS params ) {}
virtual void Params_SetResult( SFPARAMS params, SFVALUE value ) {}
virtual void Params_SetResult( SFPARAMS params, int value ) {}
virtual void Params_SetResult( SFPARAMS params, float value ) {}
virtual void Params_SetResult( SFPARAMS params, bool value ) {}
virtual void Params_SetResult( SFPARAMS params, const char* value, bool bMakeNewValue = true) {}
virtual void Params_SetResult( SFPARAMS params, const wchar_t* value, bool bMakeNewValue = true ) {}
virtual SFVALUE Params_CreateNewObject( SFPARAMS params ) { return NULL; }
virtual SFVALUE Params_CreateNewString( SFPARAMS params, const char* value ) { return NULL; }
virtual SFVALUE Params_CreateNewString( SFPARAMS params, const wchar_t* value ) { return NULL; }
virtual SFVALUE Params_CreateNewArray( SFPARAMS params, int size = -1 ) { return NULL; }

// IScaleformUI
virtual void DumpMeshCacheStats() {}
virtual void SetSingleThreadedMode( bool bSingleThreded ) {}
virtual void RunFrame( float time ) {}
virtual void AdvanceSlot( int slot ) {}
virtual bool HandleInputEvent( const InputEvent_t &event ) { return false; }
virtual bool HandleIMEEvent( size_t hwnd, unsigned int uMsg, unsigned int wParam, long lParam ) { return false; }
virtual bool PreProcessKeyboardEvent( size_t hwnd, unsigned int uMsg, unsigned int wParam, long lParam ) { return false; }
virtual void SetIMEEnabled( bool bEnabled ) {}
virtual void SetIMEFocus( int slot ) {}
virtual void ShutdownIME() {}
virtual float GetJoyValue( int slot, int stickIndex, int axis ) { return 0; }
virtual void SetSlotViewport( int slot, int x, int y, int width, int height ) {}
virtual void RenderSlot( int slot ) {}
virtual void ForkRenderSlot( int slot ) {}
virtual void JoinRenderSlot( int slot ) {}
virtual void InitSlot( int slotID, const char* rootMovie, IScaleformSlotInitController *pController ) {}
virtual void SlotRelease( int slotID ) {}
virtual void SlotAddRef( int slot ) {}
virtual void LockSlot( int slot ) {}
virtual void UnlockSlot( int slot ) {}
virtual void RequestElement( int slot, const char* elementName, ScaleformUIFunctionHandlerObject* object, const IScaleformUIFunctionHandlerDefinitionTable* tableObject ) {}
virtual void RemoveElement( int slot, SFVALUE element ) {}
virtual void InstallGlobalObject( int slot, const char* elementName, ScaleformUIFunctionHandlerObject* object, const IScaleformUIFunctionHandlerDefinitionTable* tableObject, SFVALUE *pInstalledGlobalObjectResult ) {}
virtual void RemoveGlobalObject( int slot, SFVALUE element ) {}
virtual bool SlotConsumesInputEvents( int slot ) { return false; }
virtual bool ConsumesInputEvents( void ) { return false; }
virtual bool SlotDeniesInputToGame( int slot ) { return false; }
virtual void DenyInputToGame( bool value ) {}
virtual void DenyInputToGameFromFlash( int slot, bool value ) {}
virtual void LockInputToSlot( int slot ) {}
virtual void UnlockInput( void ) {}
virtual bool AvatarImageAddRef( uint64 playerID ) { return false; }
virtual void AvatarImageRelease( uint64 playerID ) {}
virtual void AvatarImageReload( uint64 playerID, IScaleformAvatarImageProvider *pProvider = NULL ) {}
virtual void AddDeviceDependentObject( IShaderDeviceDependentObject * pObject ) {}
virtual void RemoveDeviceDependentObject( IShaderDeviceDependentObject * pObject ) {}
virtual bool InventoryImageAddRef( uint64 iItemId, IScaleformInventoryImageProvider *pGlobalInventoryImageProvider ) { return false; }
virtual void InventoryImageUpdate( uint64 iItemId, IScaleformInventoryImageProvider *pGlobalInventoryImageProvider ) {}
virtual void InventoryImageRelease( uint64 iItemId ) {}
virtual void InitInventoryDefaultIcons( CUtlVector< const char * > *vecIconDefaultNames ) {}
virtual bool ChromeHTMLImageAddRef( uint64 imageID ) { return false; }
virtual void ChromeHTMLImageUpdate( uint64 imageID, const byte* rgba, int width, int height, ::ImageFormat format ) {}
virtual void ChromeHTMLImageRelease( uint64 imageID ) {}
virtual void ForceUpdateImages() {}
virtual ButtonCode_t GetCurrentKey() { return static_cast< ButtonCode_t >( 0 ); }
virtual void SendUIEvent( const char* action, const char* eventData, int slot = 0 ) {}
virtual void InitCursor( const char* cursorMovie ) {}
virtual void ReleaseCursor( void ) {}
virtual bool IsCursorVisible( void ) { return false; }
virtual void RenderCursor( void ) {}
virtual void AdvanceCursor( void ) {}
virtual void SetCursorViewport( int x, int y, int width, int height ) {}
virtual void ShowCursor( void ) {}
virtual void HideCursor( void ) {}
virtual void PS3UseMoveCursor( void ) {}
virtual void PS3UseStandardCursor( void ) {}
virtual void PS3ForceCursorStart( void ) {}
virtual void PS3ForceCursorEnd( void ) {}
virtual void SetCursorShape( int shapeIndex ) {}
virtual void ForceCollectGarbage( int slot ) {}
virtual bool IsSetToControllerUI( int slot ) { return false; }
virtual void LockMostRecentInputDevice( int slot ) {}
virtual void ClearCache( void ) {}
virtual SFMOVIEDEF CreateMovieDef( const char* pfilename, unsigned int loadConstants = 0, size_t memoryArena = 0 ) { return NULL; }
virtual void ReleaseMovieDef( SFMOVIEDEF movieDef ) {}
virtual SFMOVIE MovieDef_CreateInstance( SFMOVIEDEF movieDef, bool initFirstFrame = true, size_t memoryArena = 0 ) { return NULL; }
virtual void ReleaseMovieView( SFMOVIE movieView ) {}
virtual void MovieView_Advance( SFMOVIE movieView, float time, unsigned int frameCatchUpCount = 2 ) {}
virtual void MovieView_SetBackgroundAlpha( SFMOVIE movieView, float alpha ) {}
virtual void MovieView_SetViewport( SFMOVIE movieView, int bufw, int bufh, int left, int top, int w, int h, unsigned int flags = 0 ) {}
virtual void MovieView_Display( SFMOVIE movieView ) {}
virtual void MovieView_SetViewScaleMode( SFMOVIE movieView, _ScaleModeType type ) {}
virtual _ScaleModeType MovieView_GetViewScaleMode( SFMOVIE movieView ) { return static_cast< _ScaleModeType >( 0 ); }
virtual void MovieView_SetViewAlignment( SFMOVIE movieView, _AlignType type ) {}
virtual _AlignType MovieView_GetViewAlignment( SFMOVIE movieView ) { return static_cast< _AlignType >( 0 ); }
virtual SFVALUE MovieView_CreateObject( SFMOVIE movieView, const char* className = NULL, SFVALUEARRAY args = SFVALUEARRAY(0, NULL), int numArgs = 0 ) { return NULL; }
virtual SFVALUE MovieView_GetVariable( SFMOVIE movieView, const char* variablePath ) { return NULL; }
virtual SFVALUE MovieView_CreateString( SFMOVIE movieView, const char *str ) { return NULL; }
virtual SFVALUE MovieView_CreateStringW( SFMOVIE movieView, const wchar_t *str ) { return NULL; }
virtual SFVALUE MovieView_CreateArray( SFMOVIE movieView, int size = -1 ) { return NULL; }
virtual const wchar_t* Translate( const char *key, bool* pIsHTML ) { return L""; }
virtual const wchar_t* ReplaceGlyphKeywordsWithHTML( const wchar_t* pin, int fontSize = 0, bool bForceControllerGlyph = false ) { return L""; }
virtual const wchar_t* ReplaceGlyphKeywordsWithHTML( const char* text, int fontSize = 0, bool bForceControllerGlyph = false ) { return L""; }
virtual void MakeStringSafe( const wchar_t* stringin, OUT_Z_BYTECAP(outlength) wchar_t* stringout, int outlength ) {}
virtual void RefreshKeyBindings( void ) {}
virtual void ShowActionNameWhenActionIsNotBound( bool value ) {}
virtual void UpdateBindingForButton( ButtonCode_t bt, const char* pbinding ) {}
virtual bool MovieView_HitTest( SFMOVIE movieView, float x, float y, _HitTestType testCond = HitTest_Shapes, unsigned int controllerIdx = 0 ) { return false; }
virtual SFVALUE CreateValue( SFVALUE value ) { return NULL; }
virtual SFVALUE CreateValue( int value ) { return NULL; }
virtual SFVALUE CreateValue( float value ) { return NULL; }
virtual SFVALUE CreateValue( bool value ) { return NULL; }
virtual SFVALUE CreateValue( const char* value ) { return NULL; }
virtual SFVALUE CreateValue( const wchar_t* value ) { return NULL; }
virtual SFVALUE CreateNewObject( int slot ) { return NULL; }
virtual SFVALUE CreateNewString( int slot, const char* value ) { return NULL; }
virtual SFVALUE CreateNewString( int slot, const wchar_t* value ) { return NULL; }
virtual SFVALUE CreateNewArray( int slot, int size = -1 ) { return NULL; }
virtual void Value_SetValue( SFVALUE obj, SFVALUE value ) {}
virtual void Value_SetValue( SFVALUE obj, int value ) {}
virtual void Value_SetValue( SFVALUE obj, float value ) {}
virtual void Value_SetValue( SFVALUE obj, bool value ) {}
virtual void Value_SetValue( SFVALUE obj, const char* value ) {}
virtual void Value_SetValue( SFVALUE obj, const wchar_t* value ) {}
virtual void Value_SetColor( SFVALUE obj, int color ) {}
virtual void Value_SetColor( SFVALUE obj, float r, float g, float b, float a ) {}
virtual void Value_SetTint( SFVALUE obj, int color ) {}
virtual void Value_SetTint( SFVALUE obj, float r, float g, float b, float a ) {}
virtual void Value_SetColorTransform( SFVALUE obj, int colorMultiply, int colorAdd ) {}
virtual void Value_SetColorTransform( SFVALUE obj, float r, float g, float b, float a, int colorAdd ) {}
virtual void Value_SetArraySize( SFVALUE obj, int size ) {}
virtual int Value_GetArraySize( SFVALUE obj ) { return 0; }
virtual void Value_ClearArrayElements( SFVALUE obj ) {}
virtual void Value_RemoveArrayElement( SFVALUE obj, int index ) {}
virtual void Value_RemoveArrayElements( SFVALUE obj, int index, int count ) {}
virtual SFVALUE Value_GetArrayElement( SFVALUE obj, int index ) { return NULL; }
virtual void Value_SetArrayElement( SFVALUE obj, int index, SFVALUE value ) {}
virtual void Value_SetArrayElement( SFVALUE obj, int index, int value ) {}
virtual void Value_SetArrayElement( SFVALUE obj, int index, float value ) {}
virtual void Value_SetArrayElement( SFVALUE obj, int index, bool value ) {}
virtual void Value_SetArrayElement( SFVALUE obj, int index, const char* value ) {}
virtual void Value_SetArrayElement( SFVALUE obj, int index, const wchar_t* value ) {}
virtual void Value_SetText( SFVALUE obj, const char* value ) {}
virtual void Value_SetText( SFVALUE obj, const wchar_t* value ) {}
virtual void Value_SetTextHTML( SFVALUE obj, const char* value ) {}
virtual void Value_SetTextHTML( SFVALUE obj, const wchar_t* value ) {}
virtual int Value_SetFormattedText( SFVALUE obj, const char* pFormat, ... ) { return 0; }
virtual void ReleaseValue( SFVALUE value ) {}
virtual void CreateValueArray( SFVALUEARRAY& valueArray, int length ) {}
virtual SFVALUEARRAY CreateValueArray( int length ) { return SFVALUEARRAY( 0, NULL ); }
virtual void ReleaseValueArray( SFVALUEARRAY& valueArray ) {}
virtual void ReleaseValueArray( SFVALUEARRAY& valueArray, int count ) {}
virtual SFVALUE ValueArray_GetElement( SFVALUEARRAY, int index ) { return NULL; }
virtual _ValueType ValueArray_GetType( SFVALUEARRAY array, int index ) { return static_cast< _ValueType >( 0 ); }
virtual double ValueArray_GetNumber( SFVALUEARRAY array, int index ) { return 0; }
virtual bool ValueArray_GetBool( SFVALUEARRAY array, int index ) { return false; }
virtual const char* ValueArray_GetString( SFVALUEARRAY array, int index ) { return ""; }
virtual const wchar_t* ValueArray_GetStringW( SFVALUEARRAY array, int index ) { return L""; }
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, SFVALUE value ) {}
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, int value ) {}
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, float value ) {}
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, bool value ) {}
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, const char* value ) {}
virtual void ValueArray_SetElement( SFVALUEARRAY, int index, const wchar_t* value ) {}
virtual void ValueArray_SetElementText( SFVALUEARRAY, int index, const char* value ) {}
virtual void ValueArray_SetElementText( SFVALUEARRAY, int index, const wchar_t* value ) {}
virtual void ValueArray_SetElementTextHTML( SFVALUEARRAY, int index, const char* value ) {}
virtual void ValueArray_SetElementTextHTML( SFVALUEARRAY, int index, const wchar_t* value ) {}
virtual bool Value_HasMember( SFVALUE value, const char* name ) { return false; }
virtual SFVALUE Value_GetMember( SFVALUE value, const char* name ) { return NULL; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, SFVALUE value ) { return false; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, int value ) { return false; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, float value ) { return false; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, bool value ) { return false; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, const char* value ) { return false; }
virtual bool Value_SetMember( SFVALUE obj, const char *name, const wchar_t* value ) { return false; }
virtual ISFTextObject* TextObject_MakeTextObject( SFVALUE value ) { return NULL; }
virtual ISFTextObject* TextObject_MakeTextObjectFromMember( SFVALUE value, const char* pName ) { return NULL; }
virtual bool Value_InvokeWithoutReturn( SFVALUE obj, const char* methodName, const SFVALUEARRAY& args ) { return false; }
virtual SFVALUE Value_Invoke( SFVALUE obj, const char* methodName, const SFVALUEARRAY& args ) { return NULL; }
virtual bool Value_InvokeWithoutReturn( SFVALUE obj, const char* methodName, SFVALUE args, int numArgs ) { return false; }
virtual SFVALUE Value_Invoke( SFVALUE obj, const char* methodName, SFVALUE args, int numArgs ) { return NULL; }
virtual bool Value_InvokeWithoutReturn( SFVALUE obj, const char* methodName, const SFVALUEARRAY& args, int numArgs ) { return false; }
virtual SFVALUE Value_Invoke( SFVALUE obj, const char* methodName, const SFVALUEARRAY& args, int numArgs ) { return NULL; }
virtual void Value_SetVisible( SFVALUE obj, bool visible ) {}
virtual void Value_GetDisplayInfo( SFVALUE obj, ScaleformDisplayInfo* dinfo ) {}
virtual void Value_SetDisplayInfo( SFVALUE obj, const ScaleformDisplayInfo* dinfo ) {}
virtual _ValueType Value_GetType( SFVALUE obj ) { return static_cast< _ValueType >( 0 ); }
virtual double Value_GetNumber( SFVALUE obj ) { return 0; }
virtual bool Value_GetBool( SFVALUE obj ) { return false; }
virtual const char* Value_GetString( SFVALUE obj ) { return ""; }
virtual const wchar_t* Value_GetStringW( SFVALUE obj ) { return L""; }
virtual SFVALUE Value_GetText( SFVALUE obj ) { return NULL; }
virtual SFVALUE Value_GetTextHTML( SFVALUE obj ) { return NULL; }
