#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'togl'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('TOGL_DLL_EXPORT',1)
	conf.env.append_unique('DEFINES',['strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead'])

def build(bld):
	source = [
		'linuxwin/dx9asmtogl2.cpp',
		'linuxwin/dxabstract.cpp',
		'linuxwin/glentrypoints.cpp',	
		'linuxwin/glmgr.cpp',			
		'linuxwin/glmgrbasics.cpp',	
		#'linuxwin/intelglmallocworkaround.cpp',		[$OSXALL]
		#'linuxwin/mach_override.c',					[$OSXALL]
		'linuxwin/cglmtex.cpp',		
		'linuxwin/cglmfbo.cpp',		
		'linuxwin/cglmprogram.cpp',	
		'linuxwin/cglmbuffer.cpp',	
		'linuxwin/cglmquery.cpp',
		'linuxwin/asanstubs.cpp',
		'linuxwin/decompress.c'
	]

	if bld.env.DEST_OS == "darwin" and not bld.env.IOS:
		source += ['linuxwin/glmgrcocoa.mm']

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	]
	if bld.env.INCLUDES_SDL2:
		includes += list(bld.env.INCLUDES_SDL2)
	if bld.env.IOS:
		includes.append('../thirdparty/SDL-src/include')
		includes.append('../thirdparty/SDL-src/src/video/khronos')
		includes.append('../common')

	defines = []
	if bld.env.IOS:
		defines += ['IOS=1', '_IOS=1']
	if bld.env.TOGLES:
		defines += ['TOGLES=1', 'DX_TO_GL_ABSTRACTION']
	if bld.env.ANGLE:
		defines += ['ANGLE=1']

	libs = ['tier0','tier1','tier2','vstdlib','mathlib']

	if bld.env.DEST_OS == "darwin" and not bld.env.IOS:
		libs += ["OPENGL", "CARBON"]

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

