#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'server'

games = {
	'hl2': ['server_base.vpc', 'server_hl2.vpc'],
	'episodic':['server_base.vpc', 'server_episodic.vpc'],
	'hl2mp': ['server_base.vpc', 'server_hl2mp.vpc'],
	'portal': ['server_base.vpc', 'server_portal.vpc'],
	'hl1': ['server_base.vpc', 'server_hl1.vpc'],
	'hl1mp': ['server_base.vpc', 'server_hl1mp.vpc'],
	'cstrike': ['server_base.vpc', 'server_cstrike.vpc', 'nav_mesh.vpc'],
	'dod': ['server_base.vpc', 'server_dod.vpc'],
	'tf': [
		'server_base.vpc',
		'server_econ_base.vpc',
		'nav_mesh.vpc',
		'server_tf.vpc'
	],
	'csgo': [
		'server_base.vpc',
		'server_econ_base.vpc',
		'server_cstrike15_inc.vpc',
	]
}

_CODE_EXTS = ('.c', '.cc', '.cpp', '.cxx')

_TF_SKIP_STEAM = (
	'ugc_utils',
	'tf_steamstats',
	'sixense/',
)

_CSGO_SKIP = (
	'steamworks_gamestats',
	'ugc_workshop',
	'workshop_manager',
	'dedicated_server_ugc',
	'sixense/',
	'/utils/common/',
	'filesystem_init.cpp',
)

def _code_sources(files, skip=()):
	out = []
	for s in files:
		low = s.replace('\\', '/').lower()
		if not low.endswith(_CODE_EXTS):
			continue
		if any(tok in low for tok in skip):
			continue
		out.append(s)
	return out

def _tf_sources():
	return [
		'../shared/tf/tf_gcmessages.cpp',
	]

def _tf_includes():
	return [
		'../../protobuf',
		'../../thirdparty/protobuf-2.6.1/src',
		'../shared/generated_proto',
		'../../public/gcsdk',
		'../../gcsdk',
		'../../gcsdk/steamextra',
		'./tf',
	]

def _csgo_proto_sources():
	return [
		'generated_proto/cstrike15_usermessages.pb.cc',
		'generated_proto/cstrike15_gcmessages.pb.cc',
		'generated_proto/base_gcmessages.pb.cc',
		'generated_proto/steammessages.pb.cc',
		'generated_proto/netmessages.pb.cc',
		'generated_proto/network_connection.pb.cc',
	]

def _csgo_includes():
	return [
		'../../protobuf',
		'../../thirdparty/protobuf-2.6.1/src',
		'./generated_proto',
		'../shared/generated_proto',
		'../../public/gcsdk',
		'../../gcsdk',
		'../../gcsdk/steamextra',
		'./cstrike15',
		'./cstrike15/bot',
		'./cstrike15/bot/states',
		'./cstrike15/hostage',
		'../shared/cstrike15',
		'../shared/cstrike15/bot',
		'../shared/econ',
	]

def _strip_defines(defines, drop):
	out = []
	for d in defines:
		key = d.split('=')[0]
		if key in drop:
			continue
		out.append(d)
	return out

def options(opt):
	return

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'../shared',
		'../../utils/common',
		'../shared/econ',
		'NextBot',
		'../../common',
		'../../public/tier0',
		'../../public/tier1',
		'../../public'
	]

	defines = []

	libs = ['tier0','particles','dmxloader','tier1','tier2','tier3','mathlib','vstdlib','choreoobjects','steam_api']
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android' and not bld.env.IOS:
		install_path += '/'+bld.env.GAMES+'/bin'

	skip = ()
	if bld.env.GAMES == 'tf':
		skip = _TF_SKIP_STEAM
	elif bld.env.GAMES == 'csgo':
		skip = _CSGO_SKIP
	source = _code_sources(game["sources"], skip) + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	defines = game["defines"]

	if bld.env.GAMES == 'tf':
		source += _tf_sources()
		includes = _tf_includes() + includes
		libs += ['gcsdk', 'protobuf']
		# Keep ENABLE_GC_MATCHMAKING so CTFGCServerSystem exists; Steam I/O is
		# disabled via NO_STEAM and stub_steam.
		defines.append('NO_STEAM=1')
	elif bld.env.GAMES == 'csgo':
		source += _csgo_proto_sources()
		includes = _csgo_includes() + includes
		libs += ['gcsdk', 'protobuf']
		defines.append('NO_STEAM=1')
		defines = _strip_defines(defines, ('INCLUDE_SCALEFORM',))

	if 'PROTECTED_THINGS_ENABLE' in defines:
		defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		install_path = install_path,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
