#!/usr/bin/env python
# Generates stub_steam/generated/<Interface>.inl: a default body for every
# method of the Steam interfaces CS:GO requests through CSteamAPIContext.
#
# CS:GO's engine and client refuse to start without a Steam client that hands
# out these interfaces and a logged-in user. stub_steam/steam_offline.cpp
# derives "null" classes from the generated bodies (every call returns an
# empty/false result) and overrides the handful of methods that describe an
# offline, logged-in user.
#
# Usage: python scripts/gen_offline_steam.py  (from the source root)

import os
import re
import sys

OUT_DIR = 'stub_steam/generated'

INTERFACES = [
	( 'isteamclient.h', 'ISteamClient' ),
	( 'isteamuser.h', 'ISteamUser' ),
	( 'isteamfriends.h', 'ISteamFriends' ),
	( 'isteamutils.h', 'ISteamUtils' ),
	( 'isteammatchmaking.h', 'ISteamMatchmaking' ),
	( 'isteammatchmaking.h', 'ISteamMatchmakingServers' ),
	( 'isteamuserstats.h', 'ISteamUserStats' ),
	( 'isteamapps.h', 'ISteamApps' ),
	( 'isteamnetworking.h', 'ISteamNetworking' ),
	( 'isteamremotestorage.h', 'ISteamRemoteStorage' ),
	( 'isteamscreenshots.h', 'ISteamScreenshots' ),
	( 'isteamhttp.h', 'ISteamHTTP' ),
	( 'isteamunifiedmessages.h', 'ISteamUnifiedMessages' ),
	( 'isteamcontroller.h', 'ISteamController' ),
	( 'isteamugc.h', 'ISteamUGC' ),
	( 'isteamapplist.h', 'ISteamAppList' ),
	( 'isteammusic.h', 'ISteamMusic' ),
	( 'isteammusicremote.h', 'ISteamMusicRemote' ),
	( 'isteamhtmlsurface.h', 'ISteamHTMLSurface' ),
	( 'isteaminventory.h', 'ISteamInventory' ),
	( 'isteamvideo.h', 'ISteamVideo' ),
]

def class_body( text, name ):
	m = re.search( r'\bclass\s+%s\b[^{;]*\{' % name, text )
	if not m:
		sys.exit( 'class %s not found' % name )
	depth, i = 1, m.end()
	while depth:
		c = text[i]
		depth += c == '{'
		depth -= c == '}'
		i += 1
	return text[m.end():i - 1]

def strip_comments( text ):
	text = re.sub( r'/\*.*?\*/', '', text, flags=re.S )
	return re.sub( r'//[^\n]*', '', text )

def default_return( ret ):
	r = ' '.join( ret.split() )
	if r == 'void':
		return None
	if re.match( r'^const\s+char\s*\*$', r ):
		return '""'
	if r.endswith( '*' ):
		return 'NULL'
	# value-initialisation: 0/false/NULL for scalars, enums and pointers,
	# the default constructor for classes such as CSteamID
	return '%s()' % r

def methods( body ):
	body = strip_comments( body )
	for m in re.finditer( r'\bvirtual\b(.*?);', body, flags=re.S ):
		decl = ' '.join( m.group( 1 ).split() )
		if not re.search( r'=\s*0\s*$', decl ):
			continue
		decl = re.sub( r'\s*=\s*0\s*$', '', decl )
		p = decl.index( '(' )
		head = decl[:p].strip()
		name = head.split()[-1].lstrip( '*&' )
		if name.startswith( '~' ):
			continue
		ret = head[:len( head ) - len( name )].strip()
		yield decl, ret

def main():
	if not os.path.isdir( OUT_DIR ):
		os.makedirs( OUT_DIR )
	total = 0
	for header, cls in INTERFACES:
		text = strip_comments( open( os.path.join( 'public/steam', header ), 'rb' ).read().decode( 'latin-1' ) )
		out = [ '// Generated by scripts/gen_offline_steam.py from public/steam/%s -- do not edit.' % header ]
		seen = set()
		for decl, ret in methods( class_body( text, cls ) ):
			if decl in seen:
				continue
			seen.add( decl )
			value = default_return( ret )
			if value is None:
				out.append( 'virtual %s {}' % decl )
			else:
				out.append( 'virtual %s { return %s; }' % ( decl, value ) )
		open( os.path.join( OUT_DIR, cls + '.inl' ), 'wb' ).write( ( '\n'.join( out ) + '\n' ).encode( 'latin-1' ) )
		print( '%-26s %3d methods' % ( cls, len( seen ) ) )
		total += len( seen )
	print( 'total %d' % total )

if __name__ == '__main__':
	main()
