#!/usr/bin/env python
# Generates scaleformui/null/nullscaleformui.inl: method bodies for a null
# IScaleformUI that accepts every call and renders nothing.
#
# CS:GO's menus and HUD are Scaleform (GFx), a prebuilt proprietary library
# that cannot be built for iOS. The game code calls IScaleformUI in many places
# without INCLUDE_SCALEFORM guards, so instead of patching every caller we keep
# INCLUDE_SCALEFORM and load this implementation: movies never load, so
# Scaleform-based panels never become ready and stay inert.
#
# Usage: python scripts/gen_null_scaleform.py  (from the source root)

import re
import sys

HEADER = 'public/scaleformui/scaleformui.h'
OUT = 'scaleformui/null/nullscaleformui.inl'
CLASSES = ('IUIMarshalHelper', 'IScaleformUI')

def class_body(text, name):
	m = re.search(r'\bclass\s+%s\b[^{;]*\{' % name, text)
	if not m:
		sys.exit('class %s not found' % name)
	depth, i = 1, m.end()
	while depth:
		c = text[i]
		depth += c == '{'
		depth -= c == '}'
		i += 1
	return text[m.end():i - 1]

def strip_comments(text):
	text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
	return re.sub(r'//[^\n]*', '', text)

def default_return(ret):
	r = ' '.join(ret.replace('virtual', '').split())
	if r == 'void':
		return None
	if r == 'bool':
		return 'false'
	if r in ('const char*', 'const char *'):
		return '""'
	if r in ('const wchar_t*', 'const wchar_t *'):
		return 'L""'
	if r.endswith('*') or r in ('SFVALUE', 'SFMOVIE', 'SFMOVIEDEF', 'SFPARAMS'):
		return 'NULL'
	if r == 'SFVALUEARRAY':
		return 'SFVALUEARRAY( 0, NULL )'
	if r in ('int', 'unsigned int', 'uint', 'uint32', 'uint64', 'int64', 'size_t',
			'float', 'double', 'short', 'unsigned short', 'char', 'unsigned char'):
		return '0'
	# enums and other scalar typedefs
	return 'static_cast< %s >( 0 )' % r

def methods(body):
	body = strip_comments(body)
	for m in re.finditer(r'\bvirtual\b(.*?);', body, flags=re.S):
		decl = ' '.join(m.group(1).split())
		if not re.search(r'=\s*0\s*$', decl):
			continue
		decl = re.sub(r'\s*=\s*0\s*$', '', decl)
		p = decl.index('(')
		head = decl[:p].strip()
		name = head.split()[-1].lstrip('*&')
		ret = head[:len(head) - len(name)].strip()
		yield decl, ret, name

def main():
	text = open(HEADER, 'rb').read().decode('latin-1')
	out = ['// Generated by scripts/gen_null_scaleform.py from %s -- do not edit.' % HEADER, '']
	seen = set()
	for cls in CLASSES:
		out.append('// %s' % cls)
		for decl, ret, name in methods(class_body(text, cls)):
			if decl in seen:
				continue
			seen.add(decl)
			value = default_return(ret)
			if value is None:
				out.append('virtual %s {}' % decl)
			else:
				out.append('virtual %s { return %s; }' % (decl, value))
		out.append('')
	open(OUT, 'wb').write('\n'.join(out).encode('latin-1'))
	print('%s: %d methods' % (OUT, len(seen)))

if __name__ == '__main__':
	main()
